### ISSUE TITLE
Focus states not accessible

### ISSUE THREAD

**Issue by DannyJoris** [mherchel/imwithherchel#2]
![imwithherchel](https://cloud.githubusercontent.com/assets/110365/17834842/5eb7e202-6729-11e6-8edb-cfa052a6ba38.gif)

You knew someone was going to do it... 😅 

For reference: https://www.lullabot.com/articles/auditing-presidential-websites-for-accessibility

**Comment by mherchel** [comment]
lol

**Comment by mherchel** [comment]
Fixed in fb7164b06e051e229692913fa19eb3e648b9cf19 Thanks @DannyJoris!
